### PR TITLE
Issue #26: Fix scheduler image and env vars

### LINKED ISSUE #26: Error while deploying model in Airflow
I'm facing this error while deploying the model onto Airflow. In AOps the model is deployed sucessfully but in Airflow I get this error:
**Broken DAG: [/usr/local/airflow/dags/61fa8e00-f14a-4dfb-ae13-9d6a73b34d70.py] No module named 'kubernetes' **

On the command line looks like python kubernetes library issue, the error is as follows:

**airflow      | [2020-12-14 09:58:37,805] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/61fa8e00-f14a-4dfb-ae13-9d6a73b34d70.py
airflow      | Traceback (most recent call last):
airflow      |   File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
airflow      |     m = imp.load_source(mod_name, filepath)
airflow      |   File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
airflow      |     module = _load(spec)
airflow      |   File "<frozen importlib._bootstrap>", line 696, in _load
airflow      |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
airflow      |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
airflow      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
airflow      |   File "/usr/local/airflow/dags/61fa8e00-f14a-4dfb-ae13-9d6a73b34d70.py", line 7, in <module>
airflow      |     from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator
airflow      |   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 24, in <module>
airflow      |     from airflow.contrib.kubernetes import kube_client, pod_generator, pod_launcher
airflow      |   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/kubernetes/pod_launcher.py", line 27, in <module>
airflow      |     from kubernetes import watch, client
airflow      | ModuleNotFoundError: No module named 'kubernetes' **

### PR DESCRIPTION
**Pull request by Christian-TD**
Fix scheduler image and env vars

Fixes #26

### CODE REVIEW

**Review by willfleury — APPROVED** [review]
Fix looks simple - but I don't understand how this fixed the issue though? What was causing the issue? The BUILD_CLIENT var wasn't used in 2.7.x ?

**Comment by Christian-TD** [comment]
> Fix looks simple - but I don't understand how this fixed the issue though? What was causing the issue? The BUILD_CLIENT var wasn't used in 2.7.x ?

Well, the main issue was that it was using the wrong airflow image (old one without Kubernetes operator). But then I found that also env.BUILD_CLIENT was missing, so the local deployer was templating the batch.py for k8s instead of docker. This is already fixed in master branch. Still there an issue with the docker container being removed just right after the batch execution, causing to throw an error in Airflow, but that requires a fix in the aoa-core:2.7.1 image, and this is fixed in 2.8.x

As soon release 2.8.0 is ready, I'll prepare the compose to use the proper versions and will check for any bug -> #20

**Comment by willfleury** [comment]
@Christian-TD I still don't see how the fix was causing the problem in 2.7.1. We don't have kubernetes usage anywhere in the 2.7.1 code base - for example here is the 2.7.1 release branch https://github.com/ThinkBigAnalytics/AoaCoreService/blob/2.7.1/aoa-serving-engines/schedulers/airflow/dags/batch.py

in it you can see we don't have any kubernetes operator usage in the batch.py so i can't see why this issue came up? 

If this has fixed it then cool but i still don't understand why :)

**Comment by Christian-TD** [comment]
> @Christian-TD I still don't see how the fix was causing the problem in 2.7.1. We don't have kubernetes usage anywhere in the 2.7.1 code base - for example here is the 2.7.1 release branch https://github.com/ThinkBigAnalytics/AoaCoreService/blob/2.7.1/aoa-serving-engines/schedulers/airflow/dags/batch.py
> 
> in it you can see we don't have any kubernetes operator usage in the batch.py so i can't see why this issue came up?
> 
> If this has fixed it then cool but i still don't understand why :)

You're right, in the 2.7.1 there is no KubernetesOperator, my guess is that in the tmp folder there where some other batch files with newer K8sOp, and he changed from one newer deployment, maybe master, to the 2.7.1; or the aoa-core:2.7.1 image has newer content (which I doubt).

**Pull request merged**
